In [1]:
from google.colab import files

In [2]:
uploaded = files.upload()

Saving Car details v3.csv to Car details v3 (1).csv

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
df = pd.read_csv("Car details v3.csv")

In [5]:
df.head()

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,torque,seats
0,Maruti Swift Dzire VDI,2014,450000,145500,Diesel,Individual,Manual,First Owner,23.4 kmpl,1248 CC,74 bhp,190Nm@ 2000rpm,5.0
1,Skoda Rapid 1.5 TDI Ambition,2014,370000,120000,Diesel,Individual,Manual,Second Owner,21.14 kmpl,1498 CC,103.52 bhp,250Nm@ 1500-2500rpm,5.0
2,Honda City 2017-2020 EXi,2006,158000,140000,Petrol,Individual,Manual,Third Owner,17.7 kmpl,1497 CC,78 bhp,"12.7@ 2,700(kgm@ rpm)",5.0
3,Hyundai i20 Sportz Diesel,2010,225000,127000,Diesel,Individual,Manual,First Owner,23.0 kmpl,1396 CC,90 bhp,22.4 kgm at 1750-2750rpm,5.0
4,Maruti Swift VXI BSIII,2007,130000,120000,Petrol,Individual,Manual,First Owner,16.1 kmpl,1298 CC,88.2 bhp,"11.5@ 4,500(kgm@ rpm)",5.0

In [6]:
df.shape

(8128, 13)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8128 entries, 0 to 8127
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   name           8128 non-null   object
 1   year           8128 non-null   int64
 2   selling_price  8128 non-null   int64
 3   km_driven      8128 non-null   int64
 4   fuel           8128 non-null   object
 5   seller_type    8128 non-null   object
 6   transmission   8128 non-null   object
 7   owner          8128 non-null   object
 8   mileage        7907 non-null   object
 9   engine         7907 non-null   object
 10  max_power      7913 non-null   object
 11  torque         7906 non-null   object
 12  seats          7907 non-null   float64
dtypes: float64(1), int64(3), object(9)
memory usage: 825.6+ KB

In [8]:
df.isnull().sum()

name               0
year               0
selling_price      0
km_driven          0
fuel               0
seller_type        0
transmission       0
owner              0
mileage          221
engine           221
max_power        215
torque           222
seats            221
dtype: int64

In [9]:
df.duplicated().sum()

np.int64(1202)

In [10]:
df = df.drop_duplicates()

In [11]:
df = df.drop(columns = ["torque"])

In [12]:
df.head()

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,seats
0,Maruti Swift Dzire VDI,2014,450000,145500,Diesel,Individual,Manual,First Owner,23.4 kmpl,1248 CC,74 bhp,5.0
1,Skoda Rapid 1.5 TDI Ambition,2014,370000,120000,Diesel,Individual,Manual,Second Owner,21.14 kmpl,1498 CC,103.52 bhp,5.0
2,Honda City 2017-2020 EXi,2006,158000,140000,Petrol,Individual,Manual,Third Owner,17.7 kmpl,1497 CC,78 bhp,5.0
3,Hyundai i20 Sportz Diesel,2010,225000,127000,Diesel,Individual,Manual,First Owner,23.0 kmpl,1396 CC,90 bhp,5.0
4,Maruti Swift VXI BSIII,2007,130000,120000,Petrol,Individual,Manual,First Owner,16.1 kmpl,1298 CC,88.2 bhp,5.0

In [13]:
df.shape

(6926, 12)

In [14]:
df['brand'] = df['name'].str.extract(r'^(\w+)')

In [15]:
df['mileage'] = df['mileage'].str.extract(r'(\d+\.?\d*)').astype(float)

In [16]:
df.head()

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,seats,brand
0,Maruti Swift Dzire VDI,2014,450000,145500,Diesel,Individual,Manual,First Owner,23.40,1248 CC,74 bhp,5.0,Maruti
1,Skoda Rapid 1.5 TDI Ambition,2014,370000,120000,Diesel,Individual,Manual,Second Owner,21.14,1498 CC,103.52 bhp,5.0,Skoda
2,Honda City 2017-2020 EXi,2006,158000,140000,Petrol,Individual,Manual,Third Owner,17.70,1497 CC,78 bhp,5.0,Honda
3,Hyundai i20 Sportz Diesel,2010,225000,127000,Diesel,Individual,Manual,First Owner,23.00,1396 CC,90 bhp,5.0,Hyundai
4,Maruti Swift VXI BSIII,2007,130000,120000,Petrol,Individual,Manual,First Owner,16.10,1298 CC,88.2 bhp,5.0,Maruti

In [17]:
df['engine'] = df['engine'].str.extract(r'(\d+\.?\d*)').astype(float)
df['max_power'] = df['max_power'].str.extract(r'(\d+\.?\d*)').astype(float)

In [19]:
df = df.drop(columns = ['name'])

In [20]:
df = df[df['seller_type'] != 'Trustmark Dealer']
df = df[df['owner'] != 'Test Drive Car']
df = df[(df['fuel'] != "LPG") & (df['fuel'] != "CNG")]

In [21]:
threshold = 30
counts = df['brand'].value_counts()
repl = counts[counts < threshold].index
df['brand'] = df['brand'].replace(repl, 'others')

In [22]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.drop('selling_price', axis=1), df['selling_price'], test_size=0.2, random_state=42)

In [36]:
_75_percentile = df['selling_price'].quantile(0.75)
_25_percentile = df['selling_price'].quantile(0.25)
min = _25_percentile - 1.5 * (_75_percentile - _25_percentile)
max = _75_percentile + 1.5 * (_75_percentile - _25_percentile)

In [38]:
y_train = y_train[(y_train >= min) & (y_train <= max)]
X_train = X_train.loc[y_train.index]

In [40]:
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.impute import KNNImputer
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.preprocessing import PowerTransformer
from sklearn.impute import SimpleImputer

In [26]:
pipe1 = Pipeline([
    ('imputer', KNNImputer(n_neighbors = 3, weights = 'distance')),
    ('scaler', StandardScaler()),
    ('normalise', PowerTransformer())
])

In [27]:
pipe2 = Pipeline([
    ('scaler2', StandardScaler()),
    ("normalise2", PowerTransformer())
])

In [28]:
pipe3 = Pipeline([
    ('ohe', OneHotEncoder(sparse_output = False, drop = 'first'))
])

In [41]:
pipe4 = Pipeline([
    ('imputer2', SimpleImputer(strategy = 'most_frequent')),
    ('ohe2', OneHotEncoder(sparse_output = False, drop = 'first', min_frequency=0.05,))
])

In [42]:
trf = ColumnTransformer([
    ('1', pipe1, ['mileage', 'engine', 'max_power']),
    ('2', pipe2, ['year', 'km_driven']),
    ('3', pipe3, ['fuel', 'seller_type', 'transmission', 'owner', 'brand']),
    ('4', pipe4, ['seats'])
], remainder = 'passthrough')

In [43]:
main_pipe = Pipeline([
    ('trf1', trf),
    ('lr', LinearRegression())
])

In [45]:
main_pipe.fit(X_train,y_train)

Pipeline(steps=[('trf1',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('1',
                                                  Pipeline(steps=[('imputer',
                                                                   KNNImputer(n_neighbors=3,
                                                                              weights='distance')),
                                                                  ('scaler',
                                                                   StandardScaler()),
                                                                  ('normalise',
                                                                   PowerTransformer())]),
                                                  ['mileage', 'engine',
                                                   'max_power']),
                                                 ('2',
                                                  Pipeline(steps=[('scaler2',
                                                                   StandardScaler()),
                                                                  ('normalise2',
                                                                   PowerTransformer())]),
                                                  ['year', 'km_driven']),
                                                 ('3',
                                                  Pipeline(steps=[('ohe',
                                                                   OneHotEncoder(drop='first',
                                                                                 sparse_output=False))]),
                                                  ['fuel', 'seller_type',
                                                   'transmission', 'owner',
                                                   'brand']),
                                                 ('4',
                                                  Pipeline(steps=[('imputer2',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('ohe2',
                                                                   OneHotEncoder(drop='first',
                                                                                 min_frequency=0.05,
                                                                                 sparse_output=False))]),
                                                  ['seats'])])),
                ('lr', LinearRegression())])

In [47]:
pred = main_pipe.predict(X_test)

In [48]:
mse = mean_squared_error(y_test, pred)
r2 = r2_score(y_test, pred)

In [68]:
mse, r2

(154945841726.43777, 0.4591693414783963)

In [59]:
test = pd.DataFrame({
    "year" : [2015],
    "km_driven" : [8000],
    "fuel" : ['Petrol'],
    "seller_type" : ['Individual'],
    "transmission" : ["Automatic"],
    "owner" : ['First Owner'],
    "mileage" : [21.0],
    "engine" : [1000],
    "max_power" : [100],
    "seats" : [4],
    "brand" : ["Skoda"]})

In [69]:
main_pipe.predict(test)

array([633129.45491677])